### ISSUE TITLE
Add templates for issues and pull requests

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#32]
GitHub, in addition to the contributing guidelines, [allows issue templates and pull request templates](https://github.com/blog/2111-issue-and-pull-request-templates).  In addition it add the ability to locate this files in the `.github` path.  We should use these in our packages (and add `.github` to `.npmignore`).

The packages to modify once the templates are in this package:

* [ ] [`dojo/core`](https://github.com/dojo/core)
* [ ] [`dojo/loader`](https://github.com/dojo/loader)
* [ ] [`dojo/dom`](https://github.com/dojo/dom)
* [ ] [`dojo/parser`](https://github.com/dojo/parser)
* [ ] [`dojo/compose`](https://github.com/dojo/compose)
* [ ] [`dojo/actions`](https://github.com/dojo/actions)
* [ ] [`dojo/i18n`](https://github.com/dojo/i18n)
* [ ] [`dojo/routing`](https://github.com/dojo/routing)
* [ ] [`dojo/crypto`](https://github.com/dojo/crypto)
* [ ] [`dojo/widgets`](https://github.com/dojo/widgets)
* [ ] [`dojo/grunt-dojo2`](https://github.com/dojo/grunt-dojo2)

**Comment by kitsonk** [comment]
@pdfernhout I think for issues, it should be something like this for issue templates:

```md
<!--
Thank you for contributing to Dojo 2.

Our issue tracker is for bugs for Dojo 2.

Please make sure you have read our Contributing Guidelines
available at: https://github.com/dojo/meta/blob/master/CONTRIBUTING.md

For general questions and discussion, please use the #dojo channel on
IRC, or submit a question on StackOverflow.

For items you believe to be defects, please provide the following information:
-->

**Version and Environment:** 

2.0.0-???

IE10 / IE11 / Edge / Chrome / Firefox / Safari / iOS / Android / NodeJS 4.1

**Code**

<!-- a self contained example of code -->

**Expected behavior:**

<!-- What did you expect to happen -->

**Actual behavior:** 

<!-- What was the actual behavior? -->
```

For pull requests, maybe something like this:

```md
<!--
Thank you for Contributing to Dojo 2.

Please make sure you have read our Contributing Guidelines
available at: https://github.com/dojo/meta/blob/master/CONTRIBUTING.md
before submitting a PR.
-->

**Type:** bug / feature

**Description:** <!-- description of the PR -->

**Related Issue:** #???

* [ ] There is a related issue
* [ ] All contributors have signed a CLA
* [ ] The code passes the CI tests
* [ ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] PR increases or maintains coverage
* [ ] Unit or Functional tests are included in the PR
* [ ] Code is reviewed and ready to be merged
```

**Comment by pdfernhout** [comment]
I created PR #41 for this.

I modified the templates slightly from the suggested ones.

For issues, I tried to ensure the environment version was included as well (e.g. Node.js 4.4.4) and that users had checked first for duplicate issues.

For pull requests, I reorganized the checklist to keep the test-related items together and suggested the user review it. I removed the reference to ensuring the code was reviewed because that is what the PR will involve and it was not clear who otherwise would be reviewing it. I also tried to clarify what maintaining coverage meant to any contributor unfamiliar with that. But if that checklist was meant for the use by the code reviewer of the PR (which it also is), then I could change it further and add back the review mention and change how the checklist is prefaced. Since it is possible the user may not include the checklist in their PR, I am not sure how to ensure the checklist is available for a reviewer if that was the intent.

I tested the issues template in a forked repo (by merging it into master), but I did not test the PR template as I was not sure how to submit a PR for a repo under my own account. Feel free to test out the PR template by opening a PR against [that repo](https://github.com/pdfernhout/dojo2-package-template).

Please let me know if you would like further changes and/or let me know when this can be rolled out to one or more other repos for use and more feedback. Quite possibly we will want to tweak these more as time goes by.

**Comment by novemberborn** [comment]
> I was not sure how to submit a PR for a repo under my own account

If you push a branch and then go to your repo it should give you the option to make a pull request.

**Comment by pdfernhout** [comment]
Thanks @novemberborn -- your suggestion worked and GitHub let me select my own repo from a dropdown for the pull request.

Here is an example pull request made using the PR template without changes:
https://github.com/pdfernhout/dojo2-package-template/pull/1

I see that the checked status of the checklist is stored somehow by GitHub. I'm not sure who has permissions to change those check statuses (perhaps anyone with repo write permission?), but I as the issue submitter can do it.

**Comment by novemberborn** [comment]
> I see that the checked status of the checklist is stored somehow by GitHub. I'm not sure who has permissions to change those check statuses (perhaps anyone with repo write permission?), but I as the issue submitter can do it.

Opened <https://github.com/pdfernhout/dojo2-package-template/pull/2>. I can edit the checklist in that one, so I think it's the user that opens the PR and anybody with write access.

**Comment by pdfernhout** [comment]
@novemberborn Thanks for testing the checklist. As repo owner, I can confirm I was able to change the state of the checkboxes in your pull request as well.

In theory, if everyone included that text with their PR, the reviewer could use it as they reviewed the pull request as part of a work flow. But since the submitter can also edit it, a flag for something like "code has been reviewed" could be changed by the PR author.

**Comment by pdfernhout** [comment]
For comparison, there is a checklist included when you submit a [TypeScript repo](https://github.com/Microsoft/TypeScript/) PR, but it is in a comment:
```
<!--
Thank you for submitting a pull request!

Here's a checklist you might find useful.
[ ] There is an associated issue that is labelled
  'Bug' or 'Accepting PRs' or is in the Community milestone
[ ] Code is up-to-date with the `master` branch
[ ] You've successfully run `jake runtests` locally
[ ] You've signed the CLA
[ ] There are new or updated unit tests validating the change

Refer to CONTRIBUTING.MD for more details.
  https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md
-->

Fixes #
```

=== And here is their issue one, again with the checklist in a comment:

    

    **TypeScript Version:** 

    1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

    **Code**

    ```ts
    // A self-contained demonstration of the problem follows...

    ```

    **Expected behavior:**

    **Actual behavior:**
